version: '3.8'
services:
  email-service:
    image: email-service
    container_name: email-service
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      aws-acess-key: "{{aws-acess-key}}"
      aws-secret-key: "{{aws-secret-key}}"
      aws-region-static: "us-east-1"